In [3]:
using LinearAlgebra

In [1]:
# Creating matrices directly
A = [1 2 3; 4 5 6; 7 8 9]  # 3x3 matrix (spaces for columns, ; for rows)

# Alternative syntax
B = [
    1 2 3
    4 5 6
    7 8 9
]

# Row vector
row_vec = [1 2 3 4]  # 1x4 matrix

# Column vector
col_vec = [1, 2, 3, 4]  # 4-element vector (not a 2D matrix)

# Or as a true column matrix
col_matrix = [1; 2; 3; 4]  # 4x1 matrix

4-element Vector{Int64}:
 1
 2
 3
 4

In [4]:
# Using built-in functions
zeros_matrix = zeros(3, 4)      # 3x4 matrix of zeros
ones_matrix = ones(2, 3)         # 2x3 matrix of ones
identity_matrix = I(3)           # 3x3 identity matrix
identity_matrix_full = Matrix(1.0I, 3, 3)  # Full 3x3 identity matrix
random_matrix = rand(3, 3)       # 3x3 random matrix (uniform [0,1])
random_normal = randn(4, 4)      # 4x4 random normal distribution

# Diagonal matrix
diag_matrix = diagm([1, 2, 3, 4])  # Diagonal matrix from vector

# Range matrices
range_matrix = reshape(1:12, 3, 4)  # 3x4 matrix with numbers 1 to 12

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [5]:
# Basic operations
C = [1 2; 3 4]
D = [5 6; 7 8]

# Addition
sum_matrix = C + D

# Subtraction
diff_matrix = C - D

# Matrix multiplication
product_matrix = C * D

# Element-wise multiplication
elementwise_product = C .* D

# Element-wise division
elementwise_div = C ./ D

# Transpose
transpose_matrix = C'  # conjugate transpose
transpose_matrix = transpose(C)  # regular transpose

# Inverse
inv_matrix = inv(C)

# Determinant
det_value = det(C)

# Trace
trace_value = tr(C)

# Eigenvalues and eigenvectors
eigen_values, eigen_vectors = eigen(C)

# Rank
rank_value = rank(C)

2

In [6]:
product_matrix = C * D

2×2 Matrix{Int64}:
 19  22
 43  50

In [7]:
elementwise_product = C .* D

2×2 Matrix{Int64}:
  5  12
 21  32

In [8]:
# Norms
norm_value = norm(C)  # Frobenius norm
norm_1 = norm(C, 1)   # L1 norm
norm_inf = norm(C, Inf)  # Infinity norm

# Condition number
cond_number = cond(C)

# Matrix powers
C_squared = C^2  # Matrix multiplication power
C_power = C^0.5  # Matrix square root (if available)

# Solving linear systems
b = [5, 6]
x = C \ b  # Solves Cx = b

# LU Decomposition
lu_factor = lu(C)

# QR Decomposition
qr_factor = qr(C)

# Singular Value Decomposition
svd_factor = svd(C)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
2×2 Matrix{Float64}:
 -0.404554  -0.914514
 -0.914514   0.404554
singular values:
2-element Vector{Float64}:
 5.464985704219043
 0.3659661906262574
Vt factor:
2×2 Matrix{Float64}:
 -0.576048  -0.817416
  0.817416  -0.576048

In [9]:
display(rand(5, 5))

5×5 Matrix{Float64}:
 0.666124  0.431055  0.613897  0.196403  0.038817
 0.961568  0.748463  0.8976    0.573478  0.38676
 0.723987  0.024837  0.411368  0.842456  0.664354
 0.745482  0.613154  0.509366  0.600689  0.88003
 0.588084  0.292196  0.816485  0.560465  0.17255