In [1]:
import numpy as np

In [2]:
import numpy as np

def column_vector(arr):
    """
    Convert array to column vector (n, 1).
    
    Parameters:
    arr: Input array (1D, 2D row, or 2D column vector)
    
    Returns:
    Column vector with shape (n, 1)
    
    Raises:
    ValueError: If input cannot be converted to a column vector
    """
    # Convert to numpy array
    arr = np.array(arr)
    
    # Case 1: 1D array - can convert to column
    if arr.ndim == 1:
        return arr.reshape(-1, 1)
    
    # Case 2: 2D array
    elif arr.ndim == 2:
        # Check if it's a valid vector (one dimension is 1)
        if arr.shape[0] == 1 and arr.shape[1] > 1:
            # Row vector -> column vector
            return arr.reshape(-1, 1)
        elif arr.shape[1] == 1 and arr.shape[0] > 1:
            # Already column vector
            return arr
        elif arr.shape[0] == 1 and arr.shape[1] == 1:
            # 1x1 scalar matrix - valid but ambiguous
            print("Warning: 1x1 matrix treated as column vector")
            return arr
        else:
            # Not a vector (both dimensions > 1)
            raise ValueError(f"Cannot convert matrix of shape {arr.shape} to column vector. Expected a vector (one dimension must be 1).")
    
    # Case 3: Higher dimensions
    else:
        raise ValueError(f"Cannot convert {arr.ndim}D array to column vector. Expected 1D or 2D array.")


def row_vector(arr):
    """
    Convert array to row vector (1, n).
    
    Parameters:
    arr: Input array (1D, 2D row, or 2D column vector)
    
    Returns:
    Row vector with shape (1, n)
    
    Raises:
    ValueError: If input cannot be converted to a row vector
    """
    # Convert to numpy array
    arr = np.array(arr)
    
    # Case 1: 1D array - can convert to row
    if arr.ndim == 1:
        return arr.reshape(1, -1)
    
    # Case 2: 2D array
    elif arr.ndim == 2:
        # Check if it's a valid vector (one dimension is 1)
        if arr.shape[1] == 1 and arr.shape[0] > 1:
            # Column vector -> row vector
            return arr.reshape(1, -1)
        elif arr.shape[0] == 1 and arr.shape[1] > 1:
            # Already row vector
            return arr
        elif arr.shape[0] == 1 and arr.shape[1] == 1:
            # 1x1 scalar matrix - valid but ambiguous
            print("Warning: 1x1 matrix treated as row vector")
            return arr
        else:
            # Not a vector (both dimensions > 1)
            raise ValueError(f"Cannot convert matrix of shape {arr.shape} to row vector. Expected a vector (one dimension must be 1).")
    
    # Case 3: Higher dimensions
    else:
        raise ValueError(f"Cannot convert {arr.ndim}D array to row vector. Expected 1D or 2D array.")


def vector_transpose(arr):
    """
    Transpose a vector (swap row and column orientation).
    
    Parameters:
    arr: Input array (1D, 2D row, or 2D column vector)
    
    Returns:
    Transposed vector with opposite orientation
    
    Raises:
    ValueError: If input cannot be interpreted as a vector
    """
    # Convert to numpy array
    arr = np.array(arr)
    
    # Case 1: 1D array
    if arr.ndim == 1:
        print("Note: 1D array treated as column vector for transpose")
        return arr.reshape(-1, 1)  # 1D -> column
    
    # Case 2: 2D array
    elif arr.ndim == 2:
        # Check if it's a valid vector
        if arr.shape[0] == 1 and arr.shape[1] > 1:
            # Row vector -> column vector
            return arr.reshape(-1, 1)
        elif arr.shape[1] == 1 and arr.shape[0] > 1:
            # Column vector -> row vector
            return arr.reshape(1, -1)
        elif arr.shape[0] == 1 and arr.shape[1] == 1:
            # 1x1 scalar - transpose is itself
            return arr
        else:
            # Not a vector
            raise ValueError(f"Cannot transpose matrix of shape {arr.shape}. Expected a vector (one dimension must be 1).")
    
    # Case 3: Higher dimensions
    else:
        raise ValueError(f"Cannot transpose {arr.ndim}D array. Expected 1D or 2D array.")


# Optional: Helper function to check if array is a valid vector
def is_vector(arr):
    """Check if array can be interpreted as a vector."""
    arr = np.array(arr)
    if arr.ndim == 1:
        return True
    elif arr.ndim == 2:
        return 1 in arr.shape  # One dimension must be 1
    else:
        return False

In [3]:
a = column_vector(np.array([1,2]))

In [4]:
a

array([[1],
       [2]])

In [5]:
ata = vector_transpose(a) @ a

In [6]:
ata

array([[5]])

In [7]:
aat = a@vector_transpose(a)

In [8]:
aat

array([[1, 2],
       [2, 4]])

In [9]:
p=aat / ata

In [10]:
b = column_vector(np.array([1,3]))

In [11]:
aat @ b / ata

array([[1.4],
       [2.8]])

In [12]:
p.T

array([[0.2, 0.4],
       [0.4, 0.8]])

In [13]:
p @ p

array([[0.2, 0.4],
       [0.4, 0.8]])

In [ ]:
a2 = 